// Column definitions, straight from ShadowPanther's original chart legends.
// Keyed by column id so any chart can pull a hover explanation for its headers.
export const COLUMN_INFO: Record<string, string> = {
  AEP: "Agility Equivalence Points — converts an item's stats into a single Agility-point value so items can be compared directly. This PVP-oriented formula gives extra weight to Stamina and defensive stats.",
  MAEP: "Maximum DPS AEP — the same Agility-point idea, tuned for maximizing PVE raid DPS.",
  TAEP: "Tank AEP — the Agility-point value tuned for avoidance tanking.",
  DPS: "Damage per second.",
  Min: "Minimum weapon damage.",
  Max: "Maximum weapon damage.",
  Avg: "Average weapon damage.",
  Source:
    "Where the item comes from: the boss that drops it, the recipe location, or the faction/quest required.",
  Loc: "Location where it's found, usually a zone's initials. BS = Blacksmithing, Enc = Enchanting, Eng = Engineering, LW = Leatherworking, R = Random World Drop.",
  P: "Phase in which the item became available.",
  Info: "Extra info such as drop %, required skill level, reputation, honor rank, or a (Q)uest item.",
  Set: "Initials of the set the armor belongs to.",
  Lvl: "Character level required to use the item.",
  H: "Which hand can use the weapon: Main-Hand, One-Hand, or Off-Hand.",
  T: "Weapon type: Sword, Mace, Fist, or Dagger.",
  B: "Bind on (P)ickup or (E)quip.",
  Sp: "Weapon speed.",
  Arm: "Armor value.",
  Agi: "Agility.",
  Sta: "Stamina.",
  Str: "Strength.",
  AP: "Attack Power.",
  Sk: "Weapon Skill.",
  Crit: "Critical strike rating.",
  Cri: "Critical strike chance (%).",
  Hit: "Hit rating / chance to hit.",
  Par: "Parry chance (%).",
  Dod: "Dodge chance (%).",
  Def: "Defense.",
  Ar: "Arcane resistance.",
  Fi: "Fire resistance.",
  Fr: "Frost resistance.",
  Na: "Nature resistance.",
  Sh: "Shadow resistance.",
  "H/5": "Health regenerated every 5 seconds.",
  HP: "Health.",
  PVP: "PVP special value.",
  PVE: "PVE special value.",
  Tank: "Tank special value.",
  Special: "Special abilities the item grants.",
  "Other Effect": "Any additional effect the enchantment provides.",
  COMPONENTS: "Materials required to craft the enchantment.",
};
